SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS TBL_CATEGORY;
 
CREATE TABLE TBL_CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  category_name VARCHAR(250)  NOT NULL 
);

DROP TABLE IF EXISTS TBL_GROCERYITEM;
 
CREATE TABLE TBL_GROCERYITEM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  grocery_name VARCHAR(250) NOT NULL,
  category_name VARCHAR(250),
  category_id INT 
  );
  
ALTER TABLE TBL_GROCERYITEM ADD FOREIGN KEY (category_id) REFERENCES TBL_CATEGORY(id);
SET FOREIGN_KEY_CHECKS=1;
